#!/usr/bin/env python
'''
Publishes a Twist to cmd_vel at a fixed frequency, using the python package to make the turtle travel in a figure-eight trajectory.

PUBLISHERS:
  + cmd_vel (geometry_msgs/Twist) at a fixed frequency, causing the turtlebot to follow the desired open-loop trajectory.

BROADCASTERS:
  + A static transfrom /tf from world to odom.

SUBSCRIPTIONS:
  + /turtle1/pose (Pose) ~ continually publishes the pose of the turtle in XY coordinates, theta, angular and linear velocities.

SERVICES:
  + /pause ~ stops the turtle in its place, logs the time it was paused at.
  + /resume ~ resumes the turtle's movement, subtracts the time paused from the calculated time so that the turtle resumes in its current place.

PARAMETERS:
  + ~pub_freq - the frequency that Twist is published to cmd_vel
  + W - the width of the figure-eight
  + H - the height of the figure-eight
  + T - the period of the turtle's travel

'''

import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg
from std_msgs.msg import String
from std_srvs.srv import Empty, EmptyResponse
from moveit_commander.conversions import pose_to_list
from interbotix_xs_modules.arm import InterbotixManipulatorXS


class Mover:
    
    def __init__(self):

        self.__reset = rospy.Service("reset", Empty, self.reset)
        self.__step = rospy.Service("step", Empty, self.step)
        self.__follow = rospy.Service("follow", Empty, self.follow)


        moveit_commander.roscpp_initialize(sys.argv)
        rospy.init_node("mover", anonymous=True)
        print("made it to init node??")
        self.group_name = "interbotix_arm"

        self.move_group = moveit_commander.MoveGroupCommander(self.group_name)

        self.scene = moveit_commander.PlanningSceneInterface()
        self.robot = moveit_commander.RobotCommander()
        print("it made it here")
        rospy.sleep(5)

        # # We can get the name of the reference frame for this robot:
        # planning_frame = move_group.get_planning_frame()
        # print("============ Planning frame: %s" % planning_frame)

        # # We can also print the name of the end-effector link for this group:
        # eef_link = move_group.get_end_effector_link()
        # print("============ End effector link: %s" % eef_link)

        # # We can get a list of all the groups in the robot:
        # group_names = robot.get_group_names()
        # print("============ Available Planning Groups:", robot.get_group_names())

        # Sometimes for debugging it is useful to print the entire state of the
        # robot:
        # print("============ Printing robot state")
        # print(robot.get_current_state())
        # print("")
        self.add_box()
        self.add_table()


        #print(get_jacobian_matrix([3,3,3,3]))

    def gotoJointTest(self):
        move_group = self.move_group #not required?

        joint_goal = move_group.get_current_joint_values()

    def wait_for_state_update(self, box_is_known=False, box_is_attached=False, timeout=4):
        
        box_name = "box"
        scene = self.scene

        start = rospy.get_time()
        seconds = rospy.get_time()
        while (seconds - start < timeout) and not rospy.is_shutdown():
            # Test if the box is in attached objects
            attached_objects = scene.get_attached_objects([box_name])
            is_attached = len(attached_objects.keys()) > 0
            # Test if the box is in the scene.
            # Note that attaching the box will remove it from known_objects
            is_known = box_name in scene.get_known_object_names()
            # Test if we are in the expected state
            if (box_is_attached == is_attached) and (box_is_known == is_known):
                return True
            # Sleep so that we give other threads time on the processor
            rospy.sleep(0.1)
            seconds = rospy.get_time()
        # If we exited the while loop without returning then we timed out
        return False

    def reset(self):
        pass

    def step(self):
        pass

    def follow(self):
        pass

    def add_box(self, timeout=0):

        box_pose = geometry_msgs.msg.PoseStamped()
        box_pose.header.frame_id = "world"
        box_pose.pose.orientation.w = 1.0
        box_pose.pose.position.z = 0.02
        box_pose.pose.position.y = 0.05  
        box_pose.pose.position.x = 0.2 
        
        box_name = "box"
        self.scene.add_box(box_name, box_pose, size=(0.14, 0.09, 0.05))
        #return self.wate_for_state_update(box_is_known=True, timeout = timeout)

    def add_table(self, timeout=0):

        box_pose = geometry_msgs.msg.PoseStamped()
        box_pose.header.frame_id = "world"
        box_pose.pose.orientation.w = 1.0
        box_pose.pose.position.z = -0.5
        box_pose.pose.position.y = 0  
        box_pose.pose.position.x = 0 
        
        box_name = "table"
        self.scene.add_box(box_name, box_pose, size=(1, 1, 1))
        #return self.wate_for_state_update(box_is_known=True, timeout = timeout)

    def move_home(self):
        self.move_group.set_named_target("Home")
        go = self.move_group.go(wait = 'true')
        self.move_group.stop()
        return


if __name__ == '__main__':
    ''' The main() function. '''
    Mover()
    rospy.spin()